### ISSUE TITLE
Make it easier to extend Camping

### ISSUE THREAD

**Issue by judofyr** [camping/camping#10]

**Comment by karloscarweber** [comment]
Hi Friends,

I've been messing around with this for a few days. A robust plugin system is already built in to Ruby. `include` and `extend` do almost all of the work required. To making Camping easier to extend we probably need to introduce lifecycle hooks into certain actions that take place, and provide clear documentation on how to write a plugin for Camping, how to encapsulate state, and how to interact with Camping's state.

If we take **Cuba**, for example, their plugin code looks like this:

```ruby
  def self.plugin(mixin)
    include mixin
    extend  mixin::ClassMethods if defined?(mixin::ClassMethods)

    mixin.setup(self) if mixin.respond_to?(:setup)
  end
```

This is pretty close to just `include`, with the added benefit of mixing in Class Methods and running a setup script. A useful addition would be before and after filters. We have a plugin for that: `CampingFilters`. You can use it like this:

```ruby
require 'camping'

Camping.goes :Nuts
module Nuts
  include CampingFilters
end
```

The downside is that the CampingFilter's plugin overwrites the service method. If we had more than one plugin that relies on service then we'd be out of luck.

I propose we build something like CampingFilter into Camping itself and give our plugins hooks for common actions:

* before and after, routes are called
* before a view lookup is performed, with an option to skip the view
* before a render is performed
* before method_missing is called in a controller (used as a Controller's dispatcher)
* etc...

I also propose we map out and document the formal Camping request sequence and available instance variables and values and how to use them. For example:

* When `@env`, `@request`, `@root`, `@input`, `@cookies`, `@state`, `@status`, `@headers`, and `@body` are set and what they contain.
* When Routes are built and fed into controllers.
* Examples for common use cases, changing headers, status, etc.. Saving `@state` in a session.
* Every method that will return the request, where to access them, and how to use them. 

I suspect that mapping out how Camping flows will give us a clear understanding of which event hooks are missing, that would be useful to add.
