### ISSUE TITLE
mruby compatibility

### ISSUE THREAD

**Issue by diclophis** [camping/camping#100]
Hello,

Is there any work being done to bring`camping` into the `mruby` community?

**Comment by judofyr** [comment]
No. mruby is too different from regular Ruby for there to be a way to support both in Camping. I don't know if anyone are working on a similar framework as Camping for mruby.

**Comment by diclophis** [comment]
Ok, bummer .... I might still try to see if there is a route towards getting mruby support by doing some syntatic changes as a separate project
