### ISSUE TITLE
Trying to understand how Middleware works.

### ISSUE THREAD

**Issue by karloscarweber** [camping/camping#115]
Hi friends,

I'm trying to fully understand what Camping is doing when it injects Middleware. Camping is rack based, so a middleware should respond to `#call`. In Camping, Apps are modules with classes that accept routes. Camping defines a function named `use`:

```ruby
# Injects a middleware:
#
#   module Blog
#     use Rack::MethodOverride
#     use Rack::Session::Memcache, :key => "session"
#   end
def use(*a, &b)
  m = a.shift.new(method(:call), *a, &b)
  meta_def(:call) { |e| m.call(e) }
end
```
earlier camping extends `Object` with `meta_def`:
```ruby
class Object
  def meta_def(m,&b)
    (class<<self;self end).send(:define_method,m,&b)
  end
end
```
This opens the Eigen Class of a module and defines a method, in our case it's `Call`. The middleware injection code first shifts the first splatted argument:
```
# if given: use Rack::MethodOverride
a.shift
# => Rack::MethodOverride
```
This also assumes that it's a class Constant that's given as the first argument. But then we immediately call `new` which instantiates the object.

What confuses me first are the parameters given to `new`: `method(:call), *a, &b)`. Does this mean that that we're creating a new object, and then making a new method called `call` that accepts the splatted arguments and an optional block?

And I'm pretty sure that's right. But then we call `meta_def`, which is implicitly called on self, which in this case would be whatever module we're currently instantiating.

So how is Camping keeping track of which middleware to call first and which to call next? Where are is the Middleware sequence stored?

**Comment by judofyr** [comment]
> So how is Camping keeping track of which middleware to call first and which to call next? Where are is the Middleware sequence stored?

The trick here is that `method(:call)` returns the _currently_ defined method. Once we call `meta_def(:call)` again then we overwrite it, but the original `method(:call)` then returns the "old" call. The whole middleware sequence is stored by those intermediate method-objects being created here.

The first time you call `use` then `method(:call)` is the original `call`-method (as defined in the source code). The second time it's the new one which was created by the previous call to `use`.

> What confuses me first are the parameters given to `new`: `method(:call), *a, &b)`. Does this mean that that we're creating a new object, and then making a new method called `call` that accepts the splatted arguments and an optional block?

So, in Rack-land then a middleware is a class which accepts an application (i.e. "something which responds to `#call`") as its first argument. The interesting thing here which makes it work is that `Method` has a method called `#call` which invokes the given. Notice that this works as well: `method(:something_else).call(123)` is the same as `something_else(123)`.

This means that the following code:

```ruby
use Rack::MethodOverride, something: :bar
```

Ends up being somewhat similar to to:

```ruby
prev_app = MyApp.method(:call)
new_app = Rack::MethodOverride.new(prev_app, something: :bar)
MyApp.meta_def(:call) { |env| new_app.call(env) }
```

**Comment by karloscarweber** [comment]
Thank you. This makes so much more sense now.

One of the other things that confused me with middleware was that it seems that my middleware was being called in reverse order.

```ruby
class Middleware1
  def initialize(app)
    @app = app
  end

  def call(env)
    puts "Middleware1 was called"
    @app.call(env)
  end
end

class Middleware2
  def initialize(app)
    @app = app
  end

  def call(env)
    puts "Middleware2 was called"
    @app.call(env)
  end
end
```

Which would mean my middleware was out of order

```
=> Middleware2 was called
=> Middleware1 was called
```

What I didn't realize was that  because of the way `#use` chained the `#call` methods Middleware are still initialized and called in the correct order:

```ruby
class Middleware1
  def initialize(app)
    puts "Middleware1 - initialized"
    @app = app
  end

  def call(env)
    puts "Middleware1 was called"
    status, headers, body = @app.call(env)
    puts "Middleware2 was resumed"
    [status, headers, body]
  end
end

class Middleware2
  def initialize(app)
    puts "Middleware2 - initialized"
    @app = app
  end

  def call(env)
    puts "Middleware2 was called"
    status, headers, body = @app.call(env)
    puts "Middleware2 was resumed"
    [status, headers, body]
  end
end
```

```
=> Middleware1 - initialized
=> Middleware2 - initialized
=> Middleware2 was called
=> Middleware1 was called
=> Middleware1 was resumed
=> Middleware2 was resumed
```

I'm going to keep this in mind when I write some documentation about how to use and write middleware for Camping.
