### ISSUE TITLE
Invoking render in a view method ?

### ISSUE THREAD

**Issue by ljulliar** [camping/camping#121]
Hi everyone,

First time testing Camping. So far I like it very much. I was just wandering if it's possible to invoke render from within a view method ? The reason I'm asking is because when I do so it seems that the instance variables initialized in the controller action doesn't seem to pass through the embedded render call. Am I missing something here ?

Thank you for your help.

**Comment by karloscarweber** [comment]
This is interesting. Perhaps provide some sample code and I can diagnose the issue.

**Comment by ljulliar** [comment]
Sure. Here is code sample below. Notes:
1) if I removed the locals argument it doesn't change a thing
2) There is no error/exception of any kind. It's just that the _ats_table partial is not rendered
3) rendar :ats (the main view) is called from an Ospweb controller as usual
4) if I call self._ats_table instead of calling render :_ats_table  it works well

```ruby
module Ospweb::Views
  def ats
    h3 "Archetypes"
    render :_ats_table, locals: { ats_stats: @ats_stats }
  end

  def _ats_table
   # some HTML rendering here using @ats_stats
  end
end
```

**Comment by karloscarweber** [comment]
Try this:

```ruby
module Ospweb::Views
  def ats
    h3 "Archetypes"
    _ats_table({ :ats_stats => @ats_stats })
  end

  def _ats_table(locals)
   # some HTML rendering here using @ats_stats
   p "Paragraph tag using some stats: #{locals[:ats_stats]}"
  end
end
```

In Markaby / Mab helper methods are immediately output when called. So you can use view helpers with `mab` as partials.

**Comment by ljulliar** [comment]
It worked well indeed. Thank you.

Le mer. 24 août 2022, 11:00, karloscarweber ***@***.***> a
écrit :
