### ISSUE TITLE
[Chore] Rubygems release

### ISSUE THREAD

**Issue by noraj** [camping/camping#134]
The last `camping` gem version on Rubygems is [2.1.532](https://rubygems.org/gems/camping/versions/2.1.532) from March 21, 2013.

Maybe 2.3 should be published there?

Also the Rubygems Homepage link points to http://camping.rubyforge.org/ which is not existing anymore, I suggest adding metadatas to the Gemspec ([example](https://github.com/noraj/haiti/blob/2db7db605591c4b877319d35a8400332d55a111f/haiti.gemspec#L22-L30)).

**Comment by karloscarweber** [comment]
Camping will be updated to Version 3.0 soon, from there we'll have updated homepage metadata in the gemspec, and hopefully regularly released minor versions.

Thank you for opening this issue.

**Comment by waghanza** [comment]
Any scheduled date / planning @karloscarweber ?

**Comment by karloscarweber** [comment]
End of March at the latest. I've been working on the website recently and will have something new live soon. After that it will be the last stretch for 3.0.

**Comment by karloscarweber** [comment]
I'm still working on this. I'm trying to get a workable baseline for [Van](https://github.com/karloscarweber/van) working first. Van is some Camping Gear that adds the Sequel gem to Camping. One of Camping 3's Goals is to make it possible to use any database system. Pulling out ActiveRecord was the first step. ActiveRecord has some Hard dependencies that prevent us from using Rack 3, which is another goal for Camping 3, So I had to "postpone" the adoption of that little gem.

Anyways, So Van should be ready soon, Camping 3 will have a release ready, then We'll finish the website and formally share with everybody.

**Comment by karloscarweber** [comment]
Camping 3.0 should be ready and released sometime in the next week.

**Comment by karloscarweber** [comment]
Camping 3.0 has been released!

**Comment by waghanza** [comment]
@karloscarweber when running `camping new ...` we have a syntax error
```ruby
camp.rb:41 syntax error, unexpected local variable or method, expecting `end'
```

**Comment by waghanza** [comment]
I have also `/gems/puma-6.2.2/lib/puma/dsl.rb:132:in `instance_eval': camp.rb:5: class/module name must be CONSTANT` when running `bundle && bundle exec puma -C camp.rb` on a bran new app (the issue above solved)

ℹ️  I am tracking changes in https://github.com/the-benchmarker/web-frameworks/pull/6289

**Comment by karloscarweber** [comment]
I think this is resolved. There was a combination of bugs. First, a syntax error in the generated `camp.rb` file. Second, the name supplied to the `camping new` command was snake cased, but not capitalized. These should both be fixed.

Also I'm nut sure if running `bundle && bundle exec puma -C camp.rb` will work properly. Camping has a small 'server' that runs all the apps together before the camp.rb file is loaded. It's preferable to run with the `camping` command.

if it's easier for testing to run in another way, or to be more standardized to follow general conventions, I can alter Camping to be more inline with general convention.

**Comment by waghanza** [comment]
`bundle exec puma` is the standard way I use to run any `ruby` app (in fact `rails`), but anyway I can customize the command

**Comment by waghanza** [comment]
please ping me here when the gem will be pushed on https://rubygems.org/ @karloscarweber

**Comment by waghanza** [comment]
still have 
```ruby
➜  app camping
Your /Users/waghnaza/.bundle/config config includes `BUNDLE_HTTPS://RUBYGEMS__PKG__GITHUB__COM/CASHBEE-TEAM/`, which contains the dash character (`-`).
This is deprecated, because configuration through `ENV` should be possible, but `ENV` keys cannot include dashes.
Please edit /Users/waghnaza/.bundle/config and replace any dashes in configuration keys with a triple underscore (`___`).
Resolving dependencies...
/Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/lib/camping/reloader.rb:103:in `load': camp.rb:5: class/module name must be CONSTANT (SyntaxError)
  module Models
       ^~~

	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/lib/camping/reloader.rb:103:in `load_file'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/lib/camping/reloader.rb:61:in `load_apps'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/lib/camping/reloader.rb:129:in `reload!'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/lib/camping/server.rb:149:in `start'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/gems/camping-3.0.1/bin/camping:10:in `<top (required)>'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/bin/camping:25:in `load'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/bin/camping:25:in `<main>'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/waghnaza/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by karloscarweber** [comment]
What is the app name that you're passing to `camping new`? Camping new requires an alphanumeric name as the name of your app. If you're passing something else, it will fail. Of course if passing something else is convention then I can improve Camping to accept the general standard.

**Comment by waghanza** [comment]
simply `app` => `camping new app`, but this is the same with `camping new my_app`
`camp.rb` looks weird
```ruby
require 'camping'

Camping.goes :my_app

module my_app
  module Models
  end

  module Controllers
    class Index
      def get
        @title = "my_app"
        render :index
      end
    end
  end

  module Helpers
  end

  module Views

    def layout
      html do
        head do
          title 'my_app'
          link :rel => 'stylesheet', :type => 'text/css',
          :href => '/styles.css', :media => 'screen'
        end
        body do
          h1 'my_app'

          div.wrapper! do
            self << yield
          end
        end
      end
    end

    def index
      h2 "Let's go Camping"
    end

  end

end
```

**Comment by waghanza** [comment]
the argument used in `camping new` should be camelized, imho

**Comment by karloscarweber** [comment]
@waghanza I completely agree. I'll change the new generator to camelize the app name.

**Comment by karloscarweber** [comment]
@waghanza I just pushed version `3.0.2` which forces camel cased app names. I've also added some tests around the method that generates and normalizes these names so it behaves expectedly.
