### ISSUE TITLE
New Spec for Routing

### ISSUE THREAD

**Issue by karloscarweber** [camping/camping#135]
Hi Friends!

I've been working on making Camping a bit more capable when building out larger applications, while maintaining a succinct API and the only really good way to do this is to add a couple of interfaces for setting up controllers/routes. So! Here is a new spec for routing in camping:

## Defining Routes
In Camping you can define routes by calling an `Object` scoped helper method:
```ruby
get '/' do
  "This is a great response that we can just receive."
end
```

These methods define a route, or routes, accept a block at the end, and match an HTTP method that corresponds with their method name. Example: `get` matches `GET`, `post` matches `POST`.

Routes defined in this way may also accept parameters, These are passed to the block as named parameters:
```ruby
get '/users/:username' do |username|
  "Welcome to #{username}'s page."
end
```

You may be familiar with this method of route definition, it's the way that Sinatra Works.

## Controller Based routing
With Camping 3  we're introducing a new Class named `Camper` That our Controller Based Routes inherit from. Having no inheritance in Camping made setting up state in our controllers, or adding certain helper methods more complicated than it needed to be. So now we have `Camper`. 

To make controllers in our apps, do the following:
```ruby
module Donuts::Controllers
  class Toot < Camper # matches '/toot' URL.
    
    # have a before block executed.
    _before -> { before_method(); another_before_method() }
		
    # have a layout helper to execute a layout for this controller.
    _layout -> { Donuts::Views::SuperLayout }
		
    def get
      "You got this."
    end
		
    def post(name="",toot="") # matches named parameters name, and toot
      tooted = Models::Toot.new(name, toot).save
      Responses::Toot::New.new(tooted) # The New Toot response will read the tooted save result and format itself accordingly.
    end
  end
end
```

Controllers also give us the advantage of having `_before`, and `_layout` helper instance_methods. Giving us a block to execute before our methods, and for setting up a layout. `_after` is also planned.

## Inheritance based routing
You can also make a route based on inheriting from a parent class:
```ruby
module Donuts::Controllers
  class Users < Camper # /users
  end
  class Account < Users # /users/account
  end
end
```

Inheriting from routes in this manner also passes along the `_before` block and `_layout`. Maybe a strip method could let us strip out some of those options if they are different based on a sub page:
```ruby
module Donuts::Controllers
  class Account < Users # /users/account
    _strip_layout() # Strips the layout
    _strip_before :before_method # Strips just that before method.
  end
end
```

## Explicit Routing
You can also set explicit routes for Camping controllers:
```ruby
module Donuts::Controllers
  # matches /users
  class Users < R '/users'
  def get
    "All the users"
  end
  end
  # matches /account and /users/account
  class Account < R '/account', '/users/account' 
    def get
      "Your account"
    end
  end
end
```

## Cascading Routes
Camping 2.3 reintroduced the idea behind multiple apps. I think it's cool as hell. An Advantage to setting up multiple apps is *including* a base app into another app, thus inheriting it's Middleware, before filters, layouts, views, etc... I had an idea that you could also inherit the root route of an inherited app, just like Controllers can inherit from one another. I wanna call this *Cascading Routes*.
```ruby
Camping.goes :Donuts # make your first Camping app. First app is scoped to '/'
module Donuts

  # Routes class or module matches a proc to a URL.
  # Do this inside of a module to capture it's instance variables and reference
  # them.
  get '/' do
    "Do something amazing!"
  end
	
  # The Donuts' app controller module
  module Controllers
    class Posts
      def get # '/posts'
        "Do something Amazing"
      end
    end
  end
	
  Camping.goes :Users # or Donuts.goes :Users
  # Users app is namespaced into Donuts Module,
  # Because it *goes* inside of the Donuts module.
  module Users::Controllers
    class Index < R '/all_users' # 
      def get
        "List all Users"
      end
    end
	
    # Make an Account app inside of the Users app.
    # not only namespaced but also a *descendant* or *child* of
    # The Users app.
    Users.goes :Account
    module Account::Controllers
      class Index < Camper # /users/account because the parent 
        def get
          "List all Users"
        end
      end
    end
  end

end
```

I also had an idea about folder based routing, but that felt a bit too complicated to implement. Maybe Save that idea to add a generic **pages** folder to your app root that holds, maybe just markdown files, and generates static pages in a camping app without requiring a Route be made somewhere in a controller.

# Camping Named Routes
Camping also does this really clever thing where the name of a camping controller denotes it's route:
```ruby
module Nuts::Controllers
  class PostMypostX < Camper # matches /post/mypost/:a_number
  end
end
```
I would love to keep this API. for a lot of reasons.

## Flattened Routes
Now that we have all of this fancy routing stuff. How do we get our routes to fire? Camping has a very simple process. Each *App* that we create is added to a `Camping::Apps` constant, an array, in the Camping Module. Our Camping Server iterates over each app, and checks against a 'urls' array for that app, trying to find a match to the current request. I love this, and I would love to keep it this simple. But in the interest in exposing exactly how Camping's routes work, and to make it much faster, I believe we should Flatten these routes.

Every time a route is created in Camping, We'll now be making a `Route` Struct. it will have a reference to the Block that's executed whent the route runs, the route to be matched, named parameters that are passed, and anything else we can think of. Most importantly it will have a reference to WHERE the route was made and if it overwrites a previously set Route. My hope is that by placing routes into an intermediate object like this, and THEN building a routing tree from it, we'll be able to expose routing to developers in a very verbose way.

Also by making routes in this manner I hope to have plugins that can set their own routes, files, and actions in our camping apps, that can then be overwritten or customized down the line.

Hoping the Routes could look something like this:

```ruby
Camping::Server.start # starts the server, but also compiles the routing tree/list thing.
Camping.Routes [
  <Route: @url="/", @proc="&Controllers::", @ancestor="Donuts">
  <Route: @url="/posts", @proc="&Donuts::Controllers::Posts", @ancestor="Donuts::Controllers">
  <Route: @url="/users", @proc="&block", @ancestor="Donuts::Users::Controllers::Index">
]
```

# to_proc

I almost forgot about this really great idea that @joeldrapper had about using `to_proc` and passing a module or class instead of a block: 

```ruby
r.on "Foo", &Foos

module Foos
  def to_proc
    method(:call).to_proc
  end
	
  def call(request)
    request.get &Index
    request.post &Create
  end
end
```

I really like this idea because procs and blocks are fast. This gives us an opportunity to also build our routes/controllers in a pleasant way, give them context and circumstance, and yet still keep things fast.

Then in your modules/classes we define `to_proc` and `call`. to_proc would just pass the request to the desired method/module/class thing; Whatever it is we want. We would then also have a place to add Before/After Filters, or even custom middleware if we chose.

Setting `to_proc` and `call` dynamically in our compile stage makes sense.

**Comment by karloscarweber** [comment]
I'd like to note that one reason I have for adding a few different ways to add Routes is so that *Camping Gear*  can add plugins to the apps they are included in without knowing too much about the app.

**Comment by katafrakt** [comment]
I have a few thoughts, since you asked on Mastodon for them:

----

```ruby
class Account < Users # /users/account
```

This resolving to `/users/account` feels a bit off and unexpected  for me. A change to the `Users` class (for example, it inheriting from yet another class) would have cascading effect downstream, probably often unexpected. I always thought of inheritance as a way of sharing behaviour, but not as affecting "magical conversions" from class names to string. If I would like to have `/users/account`, I'd rather name the class `class Users::Account`.

That being said, I'm not saying it's wrong. Just my first instinct was that I totally did not expect that.

----

```ruby
_strip_before :before_method # Strips just that before method.
```

How is this possible? The before is just a block. Is it possible to somehow hack into it and remove just one method call?

----

```ruby
Camping.goes :Users # or Donuts.goes :Users
```

I think `Donuts.goes :Users` is nicer here. It could be placed in a completely different file - if you have multiple apps you probably want to keep them in different places in the filesystem anyway. I don't quite get it how `Camping.goes :Users` should work here.

* If it's based on the fact that it's in the block of `Donuts`, it will probably make defining `Users` in a separate file less straightforward.
* If it's based on the fact that `Camping.goes` is called second time, the outcome could be affected by the loading order, which sounds quite dangerous.

----

Anyway, happy to see someone working on Camping again. It was my favourite microframework loooong time ago :wink:

**Comment by karloscarweber** [comment]
Thank you so much for responding. Here are my thoughts on some of your comments:

<hr>

> I have a few thoughts, since you asked on Mastodon for them:
> 
> ```ruby
> class Account < Users # /users/account
> ```
> 
> This resolving to `/users/account` feels a bit off and unexpected for me. A change to the `Users` class (for example, it inheriting from yet another class) would have cascading effect downstream, probably often unexpected. I always thought of inheritance as a way of sharing behaviour, but not as affecting "magical conversions" from class names to string. If I would like to have `/users/account`, I'd rather name the class `class Users::Account`.
> 

I agree with your sentiment here. It feels succinct to see it, but does break the expected convention of inheritance used to pass functionality. The idea was that you could also inherit any helpers, before or after filters, maybe even middleware. Perhaps an altered syntax could clarify this?

```ruby
  # A Camping named route inheriting from a parent controller
  # route matches: users/account because of it's name.
  class UsersAccount < Users
  end

  # An explicitly named route, also inheriting from a controller
  # if the first passed parameter to the R method is a Constant, it's inherited.
  class Account < R Users, '/account', '/users/account'
  end
```
This actually makes more sense, preserves existing functionality, and removes behaviour that could be unexpected. Honestly really great feedback, thank you.

<hr>

> ```Ruby
> _strip_before :before_method # Strips just that before method.
> ```
> 
> How is this possible? The before is just a block. Is it possible to somehow hack into it and remove just one method call?

I'm not sure. This is just an idea. Keeping the before just a block really simplifies things. Although if we wanted a specific order to the block, be able to inherit the block, or to override the block that would introduce some complexity that we may not want. maybe a plugin should handle it. So, perhaps the behaviour is that we inherit the block, but we can override it by just replacing it?

```ruby
_before -> { new_before_block_method; another_method }
```

<hr>

> ```ruby
> Camping.goes :Users # or Donuts.goes :Users
> ```
> 
> I think `Donuts.goes :Users` is nicer here. It could be placed in a completely different file - if you have multiple apps you probably want to keep them in different places in the filesystem anyway. I don't quite get it how `Camping.goes :Users` should work here.

I agree, `Donuts.goes :Users` should be the expected use case. It establishes that Donuts is Users parent. I've actually prototyped this part using a stripped down little toy program. `Camping.goes` currently copies and evals camping's core source code into a new module, (or an existing module with the name). The new behaviour extends that module with `Camping::App`, a module that is basically the Camping app equivalent. Here's some code:
```ruby
module Camping
  Apps = []

  # Camping App now will have a module we can inherit from.
  
  module App
    # Hash that says where the app was loaded from
    @_loaded = {}
    @_root = '/'
    def goes(m, g=TOPLEVEL_BINDING)
      Camping.goes(m, g, self)
    end
    def _set_parent(parent)
      @_parent = parent
    end
    def parent
      @_parent
    end
    def _loaded_from(a)
      @_loaded = a
      @_root = a[:root]
    end
    def root
      @_root
    end
  end

  class << self

    def apps
      Camping::Apps
    end

    def goes(m, g=TOPLEVEL_BINDING, parent=nil)
      pg = (parent.name.dup.to_s) << "::" if parent != nil
      f = caller[0].split("/").last.split(":")[0]
      file, line_number = f[0], f[1]
      Apps << a = eval("module #{pg}#{m.to_s}; extend Camping::App; end", g, file, line_number.to_i)
      a._set_parent(parent) if parent != nil
    
      # extremely naive way to get the parent and root. 
      # like it sucks gotta improve that.
      root = '/'+parent.name.dup.to_snake if parent != nil
      a._loaded_from( {file: file, line_number:line_number, root: root || '/'})
    end
  end
```

I wanted to preserve close to the original behaviour as possible. You can pass a `binding` into `Camping.goes` and bind the new app to a new namespace. But the idea that there should be a single place where camping apps are defined is important. Maybe we have a `camp.rb` file in the root where you make your apps *go*.
```ruby
# camp.rb
Camping.goes :Donuts
Donuts.goes :Users
```

Maybe passing a block to execute when starting the app would be cool?
```ruby
# camp.rb
Camping.goes :Donuts { |app|
  app.options.set :url_prefix, '/donuts'
}
Donuts.goes :Users { |app|
  app.options.set :url_prefix, ''
}
```

I've been thinking a lot about the loading order as well. I'm leaning to strongly encourage folx to make their apps go in `camp.rb` and that they'll load in the order they are created.

**Comment by karloscarweber** [comment]
## About that Proc Stuff
I've been thinking about how routing ought to work and the implications of using the to_proc method. I really like it and Camping's Routes should probably work like this underneath. But how exactly?

I know we're making a constructed routing tree through a compiled process, and that we have intermediate Route objects that we're making for each App/Controller/SubApp/Thing. So how do we respect inheritance, and binding actions in a predictable manner?

Maybe when we inherit an execution context, as in an App having a controller inside that also has a before block, we are really executing a proxy block that then routes our real request to the method we want to execute?

```ruby
module Donuts
  _before -> { ensure_user }
    module Controllers
    class Account < Camper
      _before -> { @account = get_account_data}
      def get
        "Welcome back #{@account.name}."
      end
    end
  end
end
```  

So in the case above both the Donuts before block and the Account before block are executed. How do we prevent that? I think we can solve that in our compile stage. We'll flag that we want to ignore the previous before block, then add our own.

```ruby
module Donuts
  _before -> {ensure_user }
  module Controllers
    class Account < Camper
      _fresh_before() # flags that we want to start fresh with our before block
      _before -> { @account = get_account_data }
      def get
        "Welcome back #{@account.name}."
      end
    end
  end
end
```

We're going to have controller inheritance and App Nesting. Ideally an inherited controller will have it's before block inherited from it's parent. If we want to add to it without replacing it we run into a problem.

```ruby
class ConnectedApps < R Account
  _before -> { @apps = get_user_apps } # get_user_apps depends on user data. But where is it? We'll error here.
  def get
    request.body = "<ul>"
    @apps.each { |a| request.body << "<li>#{a.name}<li>" }
    request.body = "</ul>"
    request.body
  end
end
```

Perhaps the solution is to append to the before?

```ruby
class ConnectedApps < R Account
  # appends to the before
  _append_before -> { @apps = get_user_apps }
end
```

This would make a new, compound proc that references the original proc then calls the new one.

What do ya'll think of this?

**Comment by karloscarweber** [comment]
# Camping Routing Spec Redux

You may define a route in a number of ways:

With a route and a block.
```ruby
# An explicit route with a block response
get '/home` { "Hello friends!" }
```

With a route and a Constant implicitly to_proc(ed) (&Thing).
```ruby
# An explicit route passed to a (Camping) Module (App)
get '/donuts', &Donuts
```

By defining a class in a Controller module, and guessing the Route from it's name.
```ruby
module Donuts
  module Controllers
  # A controller class defined in a controller module
    class Home < Camper # routes to '/home'
      def get
        "Get some donuts!!"
      end
    end 
  end
end
```

By inheriting from another controller, and guessing the route.
```ruby
# ... Donuts::Controllers
class Gallery < Home # routes to '/gallery'
end
```

By making an explicit Route in a Controller
```ruby
# ... Donuts::Controllers
class Users < R '/users' # Matches '/users'
end
```

By making an explicit route AND inheriting a controller.
```ruby
# ... Donuts::Controllers
# Inherits from Users and matches '/account', and '/users/account'
class Account < R Users, '/account', '/users/account'
end
```

# The Route Object
Defining a route Creates a `Route` Object that is then sorted and used to make a routing 'tree'.

The Camping Server uses the routing tree to direct requests to the proper block.

Routes are just execution destinations of Request objects. A request comes in and it's passed to a route. These execution destinations sometimes have middleware, and other blocks that are executed before and after they are executed. These are determined by the environment.

The Route objects aid in constructing the "block" tree that is executed. Apps have their own middleware, Controllers have before and After blocks that are executed. 

The Route construction process creates a detailed image of the routes of a project, and how they are constructed, and where the code lies, and what is executed, etc...

# Route 
-Has parent context? GO TO PARENT --->
	-Has middleware? Call that middleware.
		-Has a before block? Call it.
			-Circle back for the a current context.
			-Call the block
		-Has an After Block? Call that.
	-Middleware is called again in reverse order.
-Now Execute the thing.

A more simplified representation:
```
Request -> Call Route -> Call App -> Middleware -> Execute before -> Execute route block -> Execute After -> Return Response
```

# Nesting Camping Apps
You can nest Camping apps to inherit Middleware stacks, and to have access to helpers defined in the parent App's Namespace. Nesting Camping apps adds a url_prefix to all of the urls in the child App. Because routes are block based, it's possible to ask to override the url_prefix for a route in the nested app, or all routes. This gives us some really great complexity options.

## To do
- [ ] Figure out how a request and response object are used in all of this and how to trash state on each request. Maybe set a helper `request`, and `response` object that we pass from block to block. Or have access to in our method blocks.
- [ ] Grab the procs by calling `Method :method_name` on a controller class then executing those directly in the routing tree.
- [ ] Maybe grab Mustermann gem to parse those regular expression things, and params, and drop them into our routes and stuff. Why reinvent that? I don't want to. Do you?. But also, maybe we want to keep things simple? Need feedback on this.
- [ ] How do we establish environmental context for our routing blocks? Do we make a new controller object for each route, keep those in memory, use the `#method` method to grab the methods and then call them in our routing tree? I'm thinking yes.

**Comment by gabivoicu** [comment]
I think the best approaches for routing are #2 and #5 from your previous comment. They are the most predictable (both in terms of app behavior and developer expectations). Approach #1 could work great for a very basic response. The other approaches take an assumption/guess stab at the route and that could cause a lot of confusion and errors while developing an app.

Regarding this TODO:
>  Maybe grab Mustermann gem to parse those regular expression things, and params, and drop them into our routes and stuff. Why reinvent that? I don't want to. Do you?. But also, maybe we want to keep things simple? Need feedback on this.

Are you referring to using that gem as a way of parsing query params passed on a URL? Or something else?

**Comment by gabivoicu** [comment]
@karloscarweber
> I think we should keep this behaviour as a backwards compatible legacy thingy, but encourage the explicit routing behaviour.

This is a sound approach to me, keep backwards compatibility and encourage explicit routing moving forward.

**Comment by karloscarweber** [comment]
I've submitted a Draft PR over at #138 . I'm going to draft progress dually there and here.

I've implemented most of the new spec and added some other stuff that I should probably pull out.

There are also a lot of bug fixes and changes for the camping 3.0 release in there. 

What remains in regards to the routing spec is the `to_proc` magic of turning an App into a proc to be handled by another app. Which sounds hella cool.

**Comment by karloscarweber** [comment]
I was thinking about the `to_proc` syntax that we want for Camping apps, And It might get spicy.

Camping apps already offer a `#call` method that runs dispatch and sets up the response chain object request thingy. So just using the `&:CampingApp` to_proc wildness should just be a shortcut to `#call`. So maybe this would work:

```ruby
def to_proc
  d = self
  { |e| d(&:call) }
end
```

**Comment by karloscarweber** [comment]
I renamed FrankStyle to Nancy.

**Comment by karloscarweber** [comment]
Something interesting about it is that When you pass a to_proc to a controller in this way you get back a complete Rack Response. There is a conversion step that happens to reissue the rack response in the context of the controller that forwards to the app. Camping has a good helper that makes this easier than it otherwise would be, `#r`, which lets you set the body, headers, and status of a request.

So the manufactured controllers in Nancy, Calls the block with the event details, then interprets the response as either a string, or a rack response, (depending on if you forwarded the request to an app, or set a block directly in that environment.), then maps the response to a new response header using `#r`.

**Comment by joeldrapper** [comment]
I believe this

```ruby
def to_proc
  a = self
  proc { |e| a.call(e) }
end
```

Is equivalent to this

```ruby
def to_proc = method(:call).to_proc
```

**Comment by karloscarweber** [comment]
@joeldrapper YES IT IS! just switched it!
