### ISSUE TITLE
Rename Master Branch to Main (Again)

### ISSUE THREAD

**Issue by kaylahrose** [camping/camping#145]
## Description of Issue
There is a master (default) branch and an inactive main branch. 

## Solution

- [x] Delete the branch currently named main
- [x] Rename the master branch to main

The branch can be renamed by following these steps: 

1. Go to the repository's settings
2. Under General, Default branch, select the rename branch button (✏️pencil icon)
3. Rename branch and `main` and select the Rename Branch button

When returning to the main repo page, you will see a notice with the following content:

The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running the following commands.
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by karloscarweber** [comment]
THANK YOU! This is complete!
