### ISSUE TITLE
RubyGems page still lists camping.rubyforge.org as homepage

### ISSUE THREAD

**Issue by brandondrew** [camping/camping#156]
[The RubyGems data for Camping](https://rubygems.org/gems/camping/versions/3.1.3) is very out-of-date, listing the homepage as http://camping.rubyforge.org/

As far as I can tell there is no link anywhere there to the repo on GitHub.

**Comment by karloscarweber** [comment]
We'll be updating all of this Data within the next 7 days. We'll have a new website, although barebones, and a new official community location.

**Comment by karloscarweber** [comment]
I realize that has been a few days past the self imposed 7 days deadline. This is still on our summer list of things to do, and we'll get to it. Don't you worry.

**Comment by karloscarweber** [comment]
Recently resolved.

**Comment by brandondrew** [comment]
It's still listing the same homepage: https://rubygems.org/gems/camping/versions/3.2.4

**Comment by karloscarweber** [comment]
@brandondrew I've updated the homepage in the gem spec but the change isn't reflected on rubygems.org. I reached out to them to ask for a little help and I'll investigate a little more soon.

**Comment by karloscarweber** [comment]
@brandondrew I reached out to the folks at RubyGems. They've updated the website to reflect the new homepage, and couldn't find a root cause for why it wasn't updating based on the gemspec.
