### ISSUE TITLE
unable to run camping

### ISSUE THREAD

**Issue by arvindcj** [camping/camping#162]
I followed the Getting Started section of the book and got this error while running camping.

 $ camping
** Starting Puma on localhost:3301
/Users/sdf/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.3.0/lib/puma/launcher.rb:242:in `get_env': uninitialized constant Bundler::ORIGINAL_ENV (NameError)

        env = Bundler::ORIGINAL_ENV.dup
                     ^^^^^^^^^^^^^^
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.3.0/lib/puma/launcher.rb:184:in `run'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/puma-6.3.0/lib/rack/handler/puma.rb:76:in `run'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:341:in `start'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/camping-3.1.3/lib/camping/server.rb:150:in `start'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:182:in `start'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/camping-3.1.3/bin/camping:10:in `<top (required)>'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/bin/camping:25:in `load'
	from /Users/arvindcj/.asdf/installs/ruby/3.2.0/bin/camping:25:in `<main>'

**camping Version:** camping (3.1.3)
**Ruby Version** ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin17]

Book: https://github.com/camping/camping/blob/main/book/02_getting_started.md

Steps to reproduce 
1. gem install camping
2. follow the first step in the Getting started section.
3. Notice the error.

Btw i did notice a difference in the 'bin/camping' file present on rubygems and the main branch of github. The file looks different.

**Comment by arvindcj** [comment]
it looks like a person new to the project, needs to follow the steps in the README.md and then the book.

**Comment by karloscarweber** [comment]
@arvindcj I'll work on this and get it fixed.

**Comment by karloscarweber** [comment]
@arvindcj This should be resolved in the latest version of Camping: (3.2.4). Please let me know if you encounter this issue while using Camping again and I can fix it right away.
