### ISSUE TITLE
Receiving syntax errors when using camping

### ISSUE THREAD

**Issue by idk837384** [camping/camping#167]
I just installed camping 3.1.3 with gem install on a version of TruffleRuby compatible with Ruby 3.2.2, and whenever I try to run any camping commands I get the following error:
`
<internal:core> core/kernel.rb:266:in 'gem_original_require': /root/.gem/truffleruby/3.2.2.23.1.0/gems/camping-3.1.3/lib/camping/gear/nancy.rb:68: syntax error, unexpected '=>'
`

**Comment by karloscarweber** [comment]
Could you provide a sample app that uses the failing syntax?

**Comment by karloscarweber** [comment]
@idk837384 Could you retry this on Truffle Ruby with the latest version of Camping: (3.2.4). This should be resolved. I'll also add TruffleRuby to the ruby versions we test against.
