### ISSUE TITLE
it would be nice if the 2.2 release comes with an example how to still run multiple apps.

### ISSUE THREAD

**Issue by Bluebie** [camping/camping#63]
Since that's not a feature anymore. /via @paulvt issue #56

**Comment by karloscarweber** [comment]
I'm working on restoring this functionality in a good and default way. I've outlined some thoughts about how it could or should work in #91 . I've restored some old code that @judofyr removed to disable multiple apps and I've been iterating through a comprehensive solution that is hopefully predictable.

One requirement is to make it clear in use where each app gets mounted. To aid this I've started working on a `#routes` method for controllers. It basically parses and then spits out routes. Most of what **Camping::Controllers** does is parse and route stuff, so this is mostly a formatting utility that exposes what lies below.

Next is to have either extremely simple settings to mildly change mounting, or a simple convention mount in an order that's very clear. See #91 for more details.
