### ISSUE TITLE
Blog example fails due to ActiveRecord::RecordNotFound on the SchemaInfo 

### ISSUE THREAD

**Issue by dmitrinesterenko** [camping/camping#90]
Hi All,

I've been experimenting with Camping and in all of them was stuck at the schema migration portion. I've [recreated](https://github.com/dmitrinesterenko/camping_blog_example) the Blog example from camping/examples and added in my Gemfile.lock file as well as the blog.db database. Please consult this [repo](https://github.com/dmitrinesterenko/camping_blog_example) for the environment gem versions.

I hope this is just user error and there is something wrong with the active record versions, I couldn't find a document that outlines a particular version dependency. 

I greatly appreciate any clarification to running the example.

The resulting error is:

ActiveRecord::RecordNotFound at /
Couldn't find Blog::Models::SchemaInfo with 'id'=first

Ruby    /Users/xxxx/.rvm/gems/ruby-head/gems/activerecord-4.1.1/lib/active_record/relation/finder_methods.rb: in raise_record_not_found_exception!, line 320

**Comment by MichaelDimmitt** [comment]
rack requires Ruby version >= 2.2.2
