### ISSUE TITLE
camping server does not work as advertised.

### ISSUE THREAD

**Issue by timuckun** [camping/camping#91]
It will not automatically mount all the apps in a directory.

**Comment by DouglasAllen** [comment]
You have obviously been read the server.rb as I saw the same statement in the docs there.
While I was at it I saw where the server puts the db. This doesn't seem right. Why should the server be responsible for finding the db? We have to change this to be able to put it where we choose. please consider /config/database.yml and /db/ourdevdb.sqlite3 for one. Camping is like Rails in that it uses MVC for one and defaults to SQLite3 second and Rack third. I'm not even mentioning templates, css, and what have you. __Why is a brilliant programmer but deviates from the Ruby "convention over configuration" which seems contradictory anyway. Who says we have to do programming that way? If the Modules match up we can put the together any way we want. It's kind of like those electronic blocks that plug in to each other.

**Comment by karloscarweber** [comment]
I'm working on resolving this/trying to come up with a solution. But I think what we need to do first is determine what the desired behavior ought to be.

If we want to be able to mount more than one app, then we need to have a consistent set of rules for how they are mounted, and how the paths for each mounted app are resolved. 


I really like the idea of explicitly saying which apps are mounted by including their files.
```ruby
Camping.goes :Nuts
```
```ruby
Camping.goes :Blog
```
```ruby
require 'nuts.rb' # mounted at /nuts/
require 'blog.rb' # mounted at /blog/
```

This syntax gives us an explicit way to add configs to an app, and to mount them separately. I would like to see work. The downside is that there is no explicit way to mount a Homepage. So going to `/` would render a blank page.

To get around this we could add a special root or index class to our Controller routes, maybe even a configuration flag to mount the app at the root, or to only mount a special Class at root. `Camping::Server` could handle this.
```ruby
Camping.goes :Nuts
module Nuts
  class << self
    def config
      {:is_root => false, :has_root => true}
    end
  end
end
```
```ruby
Nuts::Controllers
  class Root
    render :root
  end
end
```
`has_root` would signify if we have a root class to handle the `/` route. `is_root` would mean that we mount this app at the root. I'm pretty sure that we could just use Camping's builtin Options to achieve this too.

It may be better to do away with this settings paradigm altogether and simply have a Camping method to set a module as the root module. In that instance the `Index` method would be the root, which is less confusing. This would also make a new standard to always set a root controller first:

```ruby
Camping.goes :Nuts
Camping.root :Nuts
```
Or hell, it might be even simpler to have the first App mounted at the root.

With multiple apps there will inevitably be route collisions. Camping would handle this well, the earliest defined route would be called and the latter ignored.

The only thing that I'm not sure about is mounting Apps within Apps. This is something that's said to be supported in the docs but doesn't actually work:

```ruby
Camping.goes :Nuts

Nuts::Controllers
    Camping.goes :Blog, binding()
end
``` 

I'm not sure how this is handled, but supporting this behavior is a good idea, I think. 

Feedback is very welcome.

**Comment by karloscarweber** [comment]
A large portion of this functionality is performed in the Camping's wrapper of Rack::Server. There we wrap the `#call(env)` method so that we can forward calls to our apps. But our apps don't have an easy way expose their routes. Having route reflection is pretty important so I'm going to try to add that.
