### ISSUE TITLE
Running migrations error

### ISSUE THREAD

**Issue by Schwad** [camping/camping#98]
Howdy!

I'm a Ruby on Rails developer who always wanted to build some `camping` apps and am currently going through your book and learning the wonderful ways of `camping`. If I become savvy enough I'm more than happy to be a contributor and community member as well.

I'm currently on [this page](https://github.com/camping/camping/blob/master/book/02_getting_started.md) at *using our model*, and when I run `camping -C nuts.rb` I receive the following error: ``raise_record_not_found_exception!': Couldn't find Nuts::Models::SchemaInfo with 'id'=first (ActiveRecord::RecordNotFound)`

Same when I try to boot up the server. 

Here is a copy of my code:

```
Camping.goes :Schwad

module Schwad::Models
  class Page < Base
  end

  #You have to manually add in each migration with a new version number and new class name.
  class BasicFields < V 1.0
    def self.up
      create_table Page.table_name do |t|
        t.string :title
        t.text   :content
        t.timestamps
      end
    end

    def self.down
      drop_table Page.table_name
    end
  end
end

def Schwad.create
  Schwad::Models.create_schema
end
```

Stacktrace:

```
/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/relation/finder_methods.rb:444:in `find_one'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/relation/finder_methods.rb:71:in `find'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/querying.rb:3:in `find'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.7/lib/active_record/core.rb:130:in `find'
	(eval):28:in `create_schema'
	nuts.rb:32:in `create'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:78:in `block in load_apps'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:66:in `each'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:66:in `inject'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:66:in `load_apps'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:124:in `reload!'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/reloader.rb:120:in `reload'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/server.rb:156:in `current_app'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/server.rb:165:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/cascade.rb:33:in `block in call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `each'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/camping-2.1.532/lib/camping/server.rb:175:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/Users/nickschwaderer/.rvm/gems/ruby-2.2.1/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by MichaelDimmitt** [comment]
did you gem install active record?
`gem install activerecord`
`gem install markaby`

I too am having an issue with active record while following the book.
but still determining if I have an actual issue.

**Comment by MichaelDimmitt** [comment]
`Blog::Models.create_schema` 
resolved the issue for myself @Schwad 

```
module Nuts::Models
  class Page < Base
  end

  class BasicFields < V 1.0
    def self.up
      create_table Page.table_name do |t|
        t.string :title
        t.text   :content
        # This gives us created_at and updated_at
        t.timestamps
      end
    end

    def self.down
      drop_table Page.table_name
    end
  end
end
Blog::Models.create_schema
```

**Comment by Schwad** [comment]
Thanks for this! Next time I'm at my machine I'll give it a try! :)

**Comment by MichaelDimmitt** [comment]
@Schwad, I think it actually has something to do with this:
https://github.com/RolifyCommunity/rolify/issues/444 rolify posts the solution at the bottom of his issue.

But I do not know where I would inherit active record in my camping application.
or if camping should be inheriting a specified version of active record.

**Comment by Schwad** [comment]
The core concern from me is from a documentation perspective. ALL example docs should work out of the box. It may be a case of finding a production-level running example app and doing a PR on the docs here. I'm not sure. Hopefully I will get a chance to play around with some of this this week. Let me know what you find out on your end....

**Comment by NoSkillGuy** [comment]
I wonder how the data is stored in models without specifying information about the database?

**Comment by judofyr** [comment]
I'd love to remove the built-in ActiveRecord support and rather let people use [activerecord_sans_rails](https://github.com/andhapp/activerecord_sans_rails) instead.

**Comment by Schwad** [comment]
REMINDME! (I wish github had that) - I'm going to properly give this a test drive in end of Jan and if it works make a documentation PR.

**Comment by karloscarweber** [comment]
> I'd love to remove the built-in ActiveRecord support and rather let people use [activerecord_sans_rails](https://github.com/andhapp/activerecord_sans_rails) instead.

It looks like `activerecord_sans_rails` is deprecated, but [standalone-migrations](https://github.com/thuss/standalone-migrations) is actively maintained and dose the same thing.

**Comment by judofyr** [comment]
+1 for removing the built-in ActiveRecord integration.

**Comment by MichaelDimmitt** [comment]
@Schwad , did this remind you?

**Comment by karloscarweber** [comment]
So, to be clear, we remove the ActiveRecord dependency, but provide a way to still easily use active record. We also make it very clear in the documentation what we're including and how to work it. We should probably have a single gem that we can inherit/use/extend to add active record models and migrations to Camping.

If we're not going to have a hard requirement of ActiveRecord then we'll also need a simple way to set the configuration of the Database.

**Comment by karloscarweber** [comment]
I think I've figured out how to do this in a good way.

First let's recap some Camping features.
* We have a Create method for when a Camping app starts up. 
* We have a way to set options in our camping apps.
* Recently we gained plugin support through Gear.

All that's missing is a small hook for plugins to include their startup command in our apps. If we add a startup hook that executes in the app's scope we can have each plugin perform a custom start command. Gear already have a Setup function that's called, but this feels like something slightly different. Honestly we could avoid the startup hooks.

With a plugin we can include everything necessary to get a database integration running, and included just by requiring that one plugin. Without explicitly including ActiveRecord in Camping we could do away with the special AR Code, and provide a blueprint for how to integrate other Database systems into Camping.

I'm going to start work on just that. 

1. I'll make a plugin that replaces the ActiveRecord integration we currently have
2. It will use the [standalone-migrations](https://github.com/karloscarweber/standalone-migrations) gem to add migrations in a bit better way.

**Comment by Schwad** [comment]
Hello in 2022! I'm an older coder, it's a blast from the past revisiting this issue. 

Looking back, am I being too bold in pushing against an activerecord dependency? Possibly. Maybe there's an argument that we can default to that and allow for other setups. 

I'm currently full-on preparing my Kaigi talk but I'd love to revisit camping to see how it's running in 2022 on Ruby 3.x to see if that changes my opinions on this subject.

I've plunked a reminder on my calendar for sep 14 after kaigi. :) 

thanks for all the conversations and interest over the years!
